```{r}
# Atribua o valor 133 para X e o valor 36 para Y. Em sequência, adicione a soma de X e Y a Z. Depois, calcule a raiz quadrada de Z e o logaritmo natural do resultado da raiz quadrada. Por fim, arredonde o resultado para zero dígitos. Qual o valor resultante ? Note que a resposta é um número inteiro.

x <- 133
y <- 36
z <- x + y

square <- sqrt(z)
res <- round(log(square), digits = 0)
res
```

```{r}
# Pesquise a respeito da “sequência de Fibonacci” (a sequência inicia com ZERO) e obtenha os cinco primeiros números dessa sequência. Qual o logarítimo natural da soma desses cinco números? (Observação: use a função round() para arredondar a resposta de modo que ela tenha apenas três casas decimais)

fib_seq <- c(0,1,1,2,3)
s <- sum(fib_seq)
res <- round(log(s), digits = 3)
res
```
```{r}
# Dada a função f(x) = sin(x) + x. Calcule o valor da derivada de primeira ordem de f(x) quando x=2. (Observação: use a função round() para arredondar a resposta de modo que ela tenha apenas três casas decimais)

d <- function(x) {
  derivative <- deriv(~ sin(x) + x, "x")
  calc <- attr(eval(derivative),"gradient")
  return (round(calc, digits = 3))
}

d(2)
```
```{r}
# Calcule o factorial de 10. Com o resultado em mãos, calcule o logaritmo de base 10 desse resultado. (Observação: use a função round() para arredondar a resposta de modo que ela tenha apenas duas casas decimais)

f <- factorial(10)
res <- round(log10(f), digits=2)
res
```

```{r}
# Suponha que a velocidade da luz seja c = 300000000 m/s. A equação da equivalência massa-energia de Einstein é dada como E=m*c^2, sendo ‘m’ a massa e ‘c’ a velocidade da luz. Calcule o logarítmo natural do valor da energia originada de um objeto de 10Kg. (Observação: use a função round() para arredondar a resposta de modo que ela tenha apenas duas casas decimais) *

c <- 300000000
m <- 10
E <- m*c^2
res <- round(log(E), digits = 2)
res
```

```{r}
# Crie um vetor de dados com o seguinte comando da linguagem R: v<-c(2,5,7,8,9) . Agora tome o seguinte polinômio f(x) = x^3 + x^2 + x. Calcule a média dos valores gerados pela função f(x) quando você substituir a variável ‘x’ do polinômio pelo vetor ‘v’.

v <- c(2,5,7,8,9)
f <- function(x) {
  return (x^3 + x^2 + x)
}
mean(f(v))

```

